os:
  - linux

language: php
dist: trusty
php:
  -'7.1'
services:
  - docker

jobs:
  include:
    -stage: "TEST"
     name: "Unit Test PHP"
     script:
      - travis_retry composer self-update
      - travis_retry composer install --prefer-source --no-interaction
      - cp .env.example .env
      - php-artisan key:generate
      - vendor/bin/phpunit tests/ExampleTest.php
    -stage: "Build Docker Image"
     name: "Build Images Docker"
     script:
      - echo "$DOCKER PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t travis-ci-build-stage-demo .
      - docker images 
      - docker tag travis-ci-build-stages-demo $DOCKER_USERNAME/cicd-lumen
      - docker push $DOCKER_USERNAME/cicd-lumen